Covid19Helpdesk/Models/Countries.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Covid19Helpdesk.Models
{
    public class Countries
    {
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string Slug { get; set; }
        public string NewConfirmed { get; set; }
        public string TotalConfirmed { get; set; }
        public string NewDeaths { get; set; }
        public string TotalDeaths { get; set; }
        public string NewRecovered { get; set; }
        public string TotalRecovered { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime Date { get; set; }
    }
}

Covid19Helpdesk/Models/Summary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Covid19Helpdesk.Models
{
    public class Summary
    {
        public Global Global { get; set; }
        public IList<Countries> Countries { get; set; }
    }
}

Covid19Helpdesk/Models/global.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Covid19Helpdesk.Models
{
    public class Global
    {
        public string NewConfirmed { get; set; }
        public string TotalConfirmed { get; set; }
        public string NewDeaths { get; set; }
        public string TotalDeaths { get; set; }
        public string NewRecovered { get; set; }
        public string TotalRecovered { get; set; }
        

    }
}

Covid19Helpdesk/Controllers/CovidHelpController.cs
using Covid19Helpdesk.Common;
using Covid19Helpdesk.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Covid19Helpdesk.Controllers
{
    public class CovidHelpController : Controller
    {
        // GET: CovidHelp
        public async Task<ActionResult> GetSummary()
        {
            Summary summary = new Summary();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(APIS.Summary);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("/summary");
                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    summary = JsonConvert.DeserializeObject<Summary>(EmpResponse);
                }
            }
            return View(summary);
        }
    }
}

Covid19Helpdesk/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Covid19Helpdesk.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Covid19Helpdesk/Views/CovidHelp/GetSummary.cshtml
@model Covid19Helpdesk.Models.Summary

@{
    ViewBag.Title = "Corona H";
}

<h2>Corona Help Desk</h2>


<div class="form-horizontal">

    <hr />
    <div class="form-group">
        <table class="table table-responsive" style="width:400px">
            <tr>
                <th>
                    New Confirmed
                </th>
                <th>
                    Total Confirmed
                </th>
                <th>
                    New Deaths
                </th>
                <th>
                    Total Deaths
                </th>
                <th>
                    New Recovered
                </th>
                <th>
                    Total Recovered
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Global.NewConfirmed)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Global.TotalConfirmed)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Global.NewDeaths)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Global.TotalDeaths)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Global.NewRecovered)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Global.TotalRecovered)
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <div class="form-group">
        <table id="table_id" class="display table table-responsive">
            <thead>
                <tr>
                    <th>
                        Country
                    </th>
                    <th>
                        Country Code
                    </th>
                    <th>
                        Slug
                    </th>
                    <th>
                        New Confirmed
                    </th>
                    <th>
                        Total Confirmed
                    </th>
                    <th>
                        New Deaths
                    </th>
                    <th>
                        Total Deaths
                    </th>
                    <th>
                        New Recovered
                    </th>
                    <th>
                        Total Recovered
                    </th>
                    <th>
                        Date
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Countries)
                {
                    int asd = 1;
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CountryCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Slug)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewConfirmed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalConfirmed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewDeaths)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalDeaths)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewRecovered)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalRecovered)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({
                //"ajax": {
                //    "url": "/CovidHelp/GetSummary",
                //    "type": "GET",
                //    "datatype": "json"
                //},
                "columns": [
                    { "data": "Country" },
                    { "data": "CountryCode" },
                    { "data": "Slug" },
                    { "data": "NewConfirmed" },
                    { "data": "TotalConfirmed" },
                    { "data": "NewDeaths" },
                    { "data": "TotalDeaths" },
                    { "data": "NewRecovered" },
                    { "data": "TotalRecovered" },
                    { "data": "Date" }
                ]
            });
        });
    </script>
}

Covid19Helpdesk/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Covid19Helpdesk/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Covid19Helpdesk/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Covid Help desk</h1>   
</div>

Covid19Helpdesk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Covid Help", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Covid help desk", "GetSummary", "CovidHelp")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Covid Help Desk</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>